catalog/urls.py
from django.conf.urls import url

from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
url(r'^profile/$', views.profile, name='profile'),
# url(r'^upload/$', views.model_form_upload, name='uploaldImage'),
# url(r'^display/(?P<id>\d+)$', views.display_document, name='displayImage'),
# url(r'^profile/edit/$', views.edit_profile, name='edit_profile'),
url(r'^$', views.index, name='index'),
url(r'^genres/$', views.GenreListView.as_view(), name='genres'),
url(r'^genre/(?P<pk>\d+)$', views.GenreDetailView.as_view(), name='genre-detail'),
url(r'^games/$', views.GameListView.as_view(), name='games'),
url(r'^game/(?P<pk>\d+)$', views.GameDetailView.as_view(), name='game-detail'),
url(r'^transactions/$', views.TransactionListView.as_view(), name='transactions'),
url(r'^transactions/(?P<pk>\d+)$', views.TransactionDetailView.as_view(), name='transaction-detail'),
url(r'^tags/$', views.TagListView.as_view(), name='tags'),
url(r'^tag/(?P<pk>\d+)$', views.TagDetailView.as_view(), name='tag-detail'),
url(r'^reward/(?P<pk>\d+)$', views.RewardDetailView.as_view(), name='reward-detail'),
]

urlpatterns += [   
url(r'^mygames/$', views.BoughtGamesByUserListView.as_view(), name='my-bought'),
url(r'^mytags/$', views.OwnedTagsByUserListView.as_view(), name='my-tags'),
url(r'^myrewards/$', views.OwnedRewardsByUserListView.as_view(), name='my-rewards'),
]


urlpatterns += [  
url(r'^game/(?P<id>\d+)/purchase/$', views.TransactionSingleCreate.as_view(), name='game-purchase'),
url(r'^game/(?P<id>\d+)/addTag/$', views.TagSingleCreate.as_view(), name='game-addTag'),
# url(r'^game/(?P<id>\d+)/addReview/$', views.ReviewCreate.as_view(), name='game-addReview'),
url(r'^transaction/create/$', views.TransactionCreate.as_view(),name='transaction-create',),
url(r'^transaction/(?P<pk>\d+)/update/$', views.TransactionUpdate.as_view(), name='transaction-update'),
url(r'^transaction/(?P<pk>\d+)/delete/$', views.TransactionDelete.as_view(), name='transaction-delete'),
]


urlpatterns += [  
url(r'^tag/create/$', views.TagCreate.as_view(), name='tag-create'),
url(r'^tag/(?P<pk>\d+)/update/$', views.TagUpdate.as_view(), name='tag-update'),
url(r'^tag/(?P<pk>\d+)/delete/$', views.TagDelete.as_view(), name='tag-delete'),
]

gamemarket/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from catalog import views as views
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static






urlpatterns = [
url(
    r'^admin/password_reset/$',auth_views.password_reset,name='admin_password_reset',
),
url(
    r'^admin/password_reset/done/$',auth_views.password_reset_done,name='password_reset_done',
),
url(
    r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
    auth_views.password_reset_confirm,
    name='password_reset_confirm',
),
url(
    r'^reset/done/$',
    auth_views.password_reset_complete,
    name='password_reset_complete',
),

    url(r'^admin/',admin.site.urls)
]


urlpatterns += [
    url(r'^catalog/', include('catalog.urls')),
]

urlpatterns += [
    url(r'^$', RedirectView.as_view(url='/catalog/', permanent=True)),
]

urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
   url(r'^accounts/signup/$', views.signup, name='signup'),
   url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # <--
]
LOGIN_URL = 'login'
LOGOUT_URL = 'logout'
LOGIN_REDIRECT_URL = 'index'


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from __future__ import unicode_literals
import time
import datetime
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
from datetime import date
import decimal
from django.urls import reverse #Used to generate URLs by reversing the URL patterns
import uuid # Required for unique book instances


class Platform(models.Model):
    name = models.CharField(max_length=200, help_text="Enter a game genre (e.g. War, Sports.)")
    def __str__(self):
        return self.name
    def display_game(self):
        return ', '.join([ game.name for game in self.game_set.all()[:10] ])
        display_game.short_description = 'Game'


class Genre(models.Model):
    name = models.CharField(max_length=200, help_text="Enter a game genre (e.g. War, Sports.)")
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('genre-detail', args=[str(self.id)])
    def display_game(self):
        return ', '.join([ game.name for game in self.game_set.all()[:10] ])
        display_game.short_description = 'Game'



class Game(models.Model):
    platform = models.ManyToManyField(Platform, help_text="Select platforms for this game")
    genre = models.ManyToManyField(Genre, help_text="Select genres for this game")
    name = models.CharField(max_length=200)
    description = models.TextField(max_length=1000, help_text="Enter a brief description of the game")
    price= models.DecimalField(max_digits=5, decimal_places=2)
    picture = models.FileField(upload_to='gamePicture/')
    featured=models.BooleanField(default=False)
    def __str__(self):
        return self.name    
    def get_purchase_url(self):
        return reverse('game-purchase', args=[str(self.id)])
    def get_addTag_url(self):
        return reverse('game-addTag', args=[str(self.id)])
    # def get_addReview_url(self):
    #     return reverse('game-addReview', args=[str(self.id)])
    def get_absolute_url(self):
        return reverse('game-detail', args=[str(self.id)])
    def display_platform(self):
        return ', '.join([ platform.name for platform in self.platform.all()[:3] ])
        display_platform.short_description = 'Platform'
    def display_genre(self):
        return ', '.join([ genre.name for genre in self.genre.all()[:3] ])
        display_genre.short_description = 'Genre'
    def display_tag(self):
        return ', '.join([ tag.name for tag in self.tag_set.all()[:3] ])
        display_tag.short_description = 'Tag'

# class Review(models.Model):
#     content = models.CharField(max_length=1000)
#     owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
#     game = models.ForeignKey(Game, on_delete=models.SET_NULL, null=True, blank=True)
#     def __str__(self):
#         return self.id

class Tag(models.Model):
    name = models.CharField(max_length=200, help_text="Enter a game tag(e.g. Excellent, Funny.)")
    game = models.ManyToManyField(Game, help_text="Select a genre for this game")
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('tag-detail', args=[str(self.id)])   
    def display_game(self):
        return ', '.join([ game.name for game in self.game.all()[:10] ])
        display_game.short_description = 'Game'     



class Transaction(models.Model):
    game = models.ManyToManyField(Game, help_text="Select the games to be bought")
    buyer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    num_reward = models.IntegerField()
    def get_absolute_url(self):
        return reverse('transaction-detail', args=[str(self.id)])
    def __str__(self):
        return str(self.id)
    def display_game(self):
        return ', '.join([ game.name for game in self.game.all()[:10] ])
        display_game.short_description = 'Game'
    def display_used_reward(self):
        return ', '.join([ str(reward.id) for reward in self.reward_set.all() ])
        display_reward.short_description = 'Reward'
    def display_origin_price(self):
        return round(sum([game.price for game in self.game.all()]),3)
    def display_trading_price(self):
        return round(sum([game.price for game in self.game.all()])*decimal.Decimal(1-0.1*self.reward_set.count()),3)

class Reward(models.Model):
    date=models.DateField( default=datetime.date.today)
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    transaction= models.ForeignKey(Transaction, blank=True,null=True)
    def __str__(self):
        return str(self.id)
    def due_date(self):
        return self.date+datetime.timedelta(days=120)
    def status(self):
        if self.transaction==None:
            if self.due_date() >datetime.date.today():
                return 'Valid'
            return 'Unvalid'
        return 'Used'
    def get_absolute_url(self):
        return reverse('reward-detail', args=[str(self.id)])  

    @staticmethod 
    def check_num(user,num):
        tmptNum=0;
        for i in Reward.objects.filter(owner=user):
            if i.status()=='Valid':
                tmptNum=tmptNum+1
        if tmptNum<num:           
            return False
        return True

    @staticmethod 
    def use_reward(user,num,trans):
        for i in range(num):
            tmpt=0
            for j in Reward.objects.filter(owner=user).order_by('date'):
                if tmpt==num:
                    return
                if j.status()=='Valid':
                    j.transaction=trans
                    j.save()
                    tmpt=tmpt+1
    @staticmethod               
    def update_reward(user):
        while sum([t.display_trading_price() for t in Transaction.objects.filter(buyer=user)])-100*(Reward.objects.filter(owner=user).count()-1)>100:
            gift = Reward( owner=user)
            gift.save()

# class Document(models.Model):
#     description = models.CharField(max_length=255, blank=True)
#     document = models.FileField(upload_to='documents/')
#     uploaded_at = models.DateTimeField(auto_now_add=True)

catalog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm
from .models import Transaction, Reward,Tag,Game
from django.forms.models import inlineformset_factory
from django.core.validators import MaxValueValidator

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')
    picture = forms.FileField(help_text='Your Icon')
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2','picture' )

class EditProfileForm(forms.Form):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email' )



# class DocumentForm(forms.ModelForm):
#     class Meta:
#         model = Document
#         fields = ('description', 'document', )

class TransactionForm(ModelForm):
    class Meta:
        model = Transaction
        fields = ('game','num_reward')
    def __init__(self, *args, **kwargs):
        buyer = kwargs.pop('owner')
        super(TransactionForm, self).__init__(*args, **kwargs)
        self.fields["game"].queryset = Game.objects.all().exclude(transaction__buyer=buyer)


class TransactionSingleForm(ModelForm):
    class Meta:
        model = Transaction
        fields = ('num_reward',)


class TagForm(ModelForm):
    class Meta:
        model = Tag
        fields = ('name','game',)
    def __init__(self, *args, **kwargs):
        buyer = kwargs.pop('owner')
        super(TagForm, self).__init__(*args, **kwargs)
        self.fields["game"].queryset = Game.objects.filter(transaction__buyer=buyer).distinct()

# class ReviewForm(ModelForm):
#     class Meta:
#         model = Review
#         fields = ('content',)
    # def __init__(self, *args, **kwargs):
    #     buyer = kwargs.pop('owner')
    #     super(TagForm, self).__init__(*args, **kwargs)
    #     self.fields["game"].queryset = Game.objects.filter(transaction__buyer=buyer).distinct()

class TagSingleForm(ModelForm):
    class Meta:
        model = Tag
        fields = ('name',)
    # def __init__(self, *args, **kwargs):
    #     buyer = kwargs.pop('owner')
    #     super(TagForm, self).__init__(*args, **kwargs)

class RewardForm(ModelForm):
    class Meta:
        model = Reward
        fields = ('date',)
    def __init__(self, *args, **kwargs):
        owner = kwargs.pop('owner')
        super(Reward, self).__init__(*args, **kwargs)
        self.fields["owner"].queryset = Subject.objects.filter(owner=owner)

RewardFormSet = inlineformset_factory(Transaction, Reward,fields=('date',), can_delete=False,form=RewardForm)

catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Author List</h1>

    {% if author_list %}
    <ul>

      {% for author in author_list %}
      <li>
        <a href="{{ author.get_absolute_url }}">{{ author.first_name }}</a> ({{author.last_name}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no authors for all the books in the library.</p>
    {% endif %}       
{% endblock %}

catalog/templates/catalog/game_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Name: {{ game.name }}</h1>


  <p><strong>Descirption:</strong> {{ game.description }}</p> 
  <p><strong>Price:</strong> {{ game.price }}</p>  
  <strong>Image:<img src="{{ game.picture.url }}"/></strong> <br></br>
  <p><strong>Platform:</strong> 

  {% for p in game.platform.all %} 
  {{ p.name }}
   {% endfor %}</p>  
  <p><strong>Genre:</strong> 

  {% for genre in game.genre.all %} 
  {{ genre }}
  {% if not forloop.last %},
   {% endif %}
   {% endfor %}</p>  



 <div style="margin-left:20px;margin-top:20px">
    <h4>Its tages</h4>

    {% for t in game.tag_set.all %}

    <hr>
<!--     <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'd' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
    {% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}
    <p><strong>Imprint:</strong> {{copy.imprint}}</p> -->
    <p class="text-muted"><strong>Tag:</strong> #{{t.name}}</p>

    {% endfor %}
  </div>

<script type="text/javascript"></script>>
{% if user.is_authenticated %}





<li><a href="{{ game.get_purchase_url }}">Buy It!!!</a>
<li><a href="{{ game.get_addTag_url }}">Add Tag</a>
<!-- <li><a href="{{ game.get_addReview_url }}">Add Review</a> -->
{% endif %}     

<!--   <div style="margin-left:20px;margin-top:20px">
    <h4>Sold in Transactions</h4>

    {% for t in game.transaction_set.all %}

    <hr>

    <p class="text-muted"><strong>Id:</strong> #{{t.id}}</p>

    {% endfor %}
  </div> -->
{% endblock %}

catalog/templates/catalog/genre_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Genre Name: {{ genre.name }}</h1>

 

  <p><strong>Games in This Genre:</strong> 

  {% for g in genre.game_set.all %} 
      <li>
        <a href="{{ g.get_absolute_url }}">{{ g.name }}</a> 
      </li>
  {% if not forloop.last %},
   {% endif %}
   {% endfor %}</p>  

<!--   <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in game.transaction_set.all %}

    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'd' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
    {% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}
    <p><strong>Imprint:</strong> {{copy.imprint}}</p>
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>


    {% endfor %}
  </div> -->
{% endblock %}

catalog/templates/catalog/genre_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Genre List</h1>

    {% if genre_list %}
    <ul>

      {% for genre in genre_list %}
      <li>
        <a href="{{ genre.get_absolute_url }}">{{ genre.name }}</a> 
      </li>
      {% endfor %}

    </ul>
    {% else %}
    <p>There are no genres in the market.</p>
    {% endif %}       
{% endblock %}

catalog/templates/catalog/profile.html
{% extends "base_generic.html" %}
{% block content %}
  <!-- <h1>Author: {{ author.first_name }}, {{ author.last_name }}</h1>
 -->
  <!-- <p><strong>Author:</strong> <a href="">{{ book.author }}</a></p> <!-- author detail link not yet defined --> 
    {% if user.is_authenticated %}


  <p><strong>First Name:</strong> {{first_name}} </p>
   <p><strong>Last Name:</strong> {{last_name}} </p>
     <p><strong>E-Mail:</strong> {{email}} </p>
<!--  'username', 'first_name', 'last_name', 'email' -->
  {% endif %} 
{% endblock %}

catalog/templates/catalog/purchase.html
{% extends "base_generic.html" %}
{% block content %}

   
    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form }}
        </table>
        <input type="submit" value="Submit" />
    </form>

{% endblock %}

catalog/templates/catalog/reward_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>ID: {{ reward.id }}</h1>

 

  <p><strong>Reward Info:</strong> </p>
Amount:{{reward.amount}}<br></br>
Owner:{{reward.owner}}<br></br>
Status:{{reward.status}}<br></br>

<!--   <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in game.transaction_set.all %}

    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'd' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
    {% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}
    <p><strong>Imprint:</strong> {{copy.imprint}}</p>
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>


    {% endfor %}
  </div> -->
{% endblock %}

catalog/templates/catalog/reward_list_owned_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>My Rewards</h1>

    {% if reward_list %}
    <ul>

<script>
  index = 1;
</script>
      {% for reward in reward_list %} 
<!--       class="{% if bookinst.is_overdue %}text-danger{% endif %}"
 -->      <li >
No <script>
  document.write(index);
</script>.
<script>
  index = index+1;
</script>Reward
     <br>  Received Date:{{ reward.date }}
     <br>   Due Date:{{ reward.due_date }}   
      <br>  Status:{{ reward.status }} 
      </li>



      {% endfor %}
    </ul>
    {% else %}
      <p>You have no rewards.</p>
    {% endif %}       
{% endblock %}

catalog/templates/catalog/signup.html
{% extends "base_generic.html" %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}

catalog/templates/catalog/tag_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Name: {{ tag.name }}</h1>

 

  <p><strong>Games with This Tag:</strong> 

  {% for g in tag.game.all %} 
      <li>
        <a href="{{ g.get_absolute_url }}">{{ g.name }}</a> 
      </li>
  {% if not forloop.last %},
   {% endif %}
   {% endfor %}</p>  

<!--   <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in game.transaction_set.all %}

    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'd' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
    {% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}
    <p><strong>Imprint:</strong> {{copy.imprint}}</p>
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>


    {% endfor %}
  </div> -->
{% endblock %}

catalog/templates/catalog/tag_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Tag List</h1>

    {% if tag_list %}
    <ul>

      {% for tag in tag_list %}
      <li>
        <a href="{{ tag.get_absolute_url }}">{{ tag.name }}</a> 
      </li>
      {% endfor %}

    </ul>
    {% else %}
    <p>There are no tags in the market.</p>
    {% endif %}       
{% endblock %}

catalog/templates/catalog/tag_list_owned_user.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Added Tags</h1>

{% if tag_list %}
<ul>
  {% for tag in tag_list %} 
<!--       class="{% if bookinst.is_overdue %}text-danger{% endif %}"



-->    
<p>Tag- {{tag.name}}:</p>
{% for game in tag.game.all %} 
<li >

<a href="{% url 'game-detail' game.pk %}">{{game.name}}</a>     
</li>
{% endfor %}
{% endfor %}
</ul>

{% else %}
<p>You have added zero tags.</p>
{% endif %}       
{% endblock %}

catalog/templates/catalog/transaction_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Author</h1>

<p>Are you sure you want to delete the transaction: {{ transaction }}?</p>

<form transaction="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

catalog/templates/catalog/transaction_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <!-- <h1>Author: {{ author.first_name }}, {{ author.last_name }}</h1>
 -->
  <!-- <p><strong>Author:</strong> <a href="">{{ book.author }}</a></p> <!-- author detail link not yet defined --> 
  <p><strong>Transaction:</strong>  </p>
 

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for game in transaction.game.all %}
    <hr>


    <p class="text-muted"><strong>Game Name:</strong> {{game.name}}</p>
    {% endfor %}
  </div>
{% endblock %}